### ISSUE TITLE
How to get gene_set_dictionary from custom KnowledgeBase required for Spectra?

### ISSUE THREAD

**Issue by caitsimop** [wallet-maker/cytopus#10]
Hi there! Me again 😄 

I was successful at created a curated KnowledgeBase for my data (think). I'm trying to use it with Spectra now but am unsure how to get the required `gene_set_dictionary` from the KnowledgeBase. Looking for the equivalent to `annotations = spc.default_gene_sets.load()`

Thank you!

**Comment by caitsimop** [comment]
In case anyone was stuck like me, this is how:

`G.get_celltype_processes(celltype_of_interest,global_celltypes = global_celltypes,get_children=True,get_parents =False)`

**Comment by wallet-maker** [comment]
Yes, this is the correct method. I guess this answers your question? Feel free to reopen if not.
