### ISSUE TITLE
How to get metadata of the Knowledge Base?

### ISSUE THREAD

**Issue by YuliaInn** [wallet-maker/cytopus#15]
I checked this github page a couple of weeks ago and saw a snapshot of the KB's metadata with columns like 'gene set', 'cell-specific', 'source', 'gene set type', 'license', 'author', etc. I guess something has changed since then. Could you please share a script to get such metadata for the default Cytopus KB?

**Comment by wallet-maker** [comment]
Hi there,

thanks for using Cytopus. Sure, you can just access the gene set node to access all its attached metadata.

Please let me know if this helps! 

Thanks,
Thomas 

```
#access metadata for a specific gene set
G.graph.nodes['Mac_LPS_response']
```

The KnowledgeBase object can also store metadata about the gene sets. In our default knowledge bases this includes:
```

'''
'version_id': str,  format: 'v_' + species in {hs, mm} for homo sapiens, mus musculus respectively + ascending int number,
 'author': str, acronym for author surname + first letter of first name,
 'license': str, license type (e.g. MIT license)
 'license_link': str, URL where original license can be found
 'license_type': str, whether license allows commercial&non-commercial 'c', or non-commercial 'nc' use only.
 'gene_set_type': str, whether the gene set was curated from literated 'curated', or curated from a perturbation experiment with RNA readout 'bulk_curated'
 'gene_set_topic': str, general topic the gene set belong too 
'''

```
We provide the information to the best of our knowledge. 
However, we cannot guarantee that licensing information is accurate, it is in the resposibility of the authors to verify that this.

**Comment by YuliaInn** [comment]
thank you. Is there any way to get a full dataset like here:

![Screenshot 2024-09-22 at 8 13 18 PM](https://github.com/user-attachments/assets/13c5af5f-7e74-493d-8c15-6b49e0652399)

? 

In Spectra paper, the authors say "We retrieved a total of 198 input gene sets from the newest version of our Cytopus knowledge base", I would like to look through those gene sets to decide which ones I want to use for my analysis. What is the best way to do it?

**Comment by wallet-maker** [comment]
Sure! you can create a dataframe to get an overview through:

```
#import knowledge base
import cytopus as cp
G = cp.kb.KnowledgeBase()

#access metadata for all gene sets
gene_set_metadata = pd.DataFrame.from_dict(dict(G.graph.nodes(data=True)), orient='index')

#subset to cellular processes
gene_set_metadata_processes = gene_set_metadata[~gene_set_metadata['class'].isin(['cell_type','gene'])]
gene_set_metadata_processes
```

**Comment by YuliaInn** [comment]
awesome. Thank you!
