### ISSUE TITLE
How to get the factors (or gene sets) about breast cancer?

### ISSUE THREAD

**Issue by BugCodeHub** [wallet-maker/cytopus#8]
This is an interesting project. I currently have breast cancer data and would like to use Cytopus to obtain factors and gene sets related to breast cancer. However, it seems that the Cytopus database only provides information about CRC (colorectal carcinoma) cells and NSCLC (non-small cell lung carcinoma) cells. Could you please provide guidance on how to obtain factors related to breast cancer?

**Comment by wallet-maker** [comment]
Hi, thanks for your interest. Yes, we have not made a serious effort for cancer cells yet. Everything is very much immune centered (which I appreciate is not ideal for the broad basis of potential users). I think the best way to get high quality gene sets are well-controlled perturbation experiments with scRNAseq readout. If this is not available, either bulk RNAseq data from sorted cells, or curating genes regulated at the transcript level in a specific process you are interested in generally works well. The latter is a lot of work though. 

Feel free to reach out via email t.walle@dkfz.de . 

We are very much interested in broadening the focus of cytopus :)

**Comment by BugCodeHub** [comment]
Thank you for your response and the suggestions provided. 

If I have any further questions, I'll seek your guidance.
