### ISSUE TITLE
Is it possible to have an editable csv or txt file of the knowledge base?

### ISSUE THREAD

**Issue by caitsimop** [wallet-maker/cytopus#9]
Hi there!

Thank you so much for making the knowledge base! I'm so excited to use it. 

I wanted to make use of this knowledge base, but my data is not solely focused on leukocytes/immune cells. I was looking for an "easy" way to browse all the datasets + cell types and be able to remove the cell types that aren't applicable, and add new gene  sets that are applicable. 

I saw the tutorial on how to make your own knowledge base, but I'm interested in _adding_ and _editing_ the Cytopus knowledge base. 

Is this something that is possible? I was browsing files [like this](https://github.com/wallet-maker/cytopus/blob/main/cytopus/data/Cytopus_1.31.txt), but it seems like it's not in a human readable format.

Thanks for the help!

**Comment by wallet-maker** [comment]
Thank you for your feedback! 

Can you check out the 'remove_circular_imports' branch?

I added some helper functions to retrieve the csv files to build the knowledge base from an existing knowledge base. You can then modify these csv files and rebuild the knowledge base. Directly modifying the knowledge base object is also possible but currently very error prone so we havent implemented it. We are planning to do so in the future though.

You can find an edited tutorial how to use the helper functions here:


https://github.com/wallet-maker/cytopus/blob/remove_circular_imports/notebooks/Cytopus_utils_tutorial.ipynb

Note that in this branch the import syntax has changed compared to the pypi version. So you have to install the branch from source. It also fixes some other issues with circular imports which we fixed on pypi but not in the github repo.

**Comment by caitsimop** [comment]
Oh this is awesome! Thank you so much! I will try this out today 😄
